config/routes.rb
Rails.application.routes.draw do
  resources :notices

  root 'notices#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/notice.rb
class Notice < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/notices_controller.rb
class NoticesController < ApplicationController
  before_action :set_notice, only: [:show, :edit, :update, :destroy]

  # GET /notices
  # GET /notices.json
  def index
    @notices = Notice.all
  end

  # GET /notices/1
  # GET /notices/1.json
  def show
  end

  # GET /notices/new
  def new
    @notice = Notice.new
  end

  # GET /notices/1/edit
  def edit
  end

  # POST /notices
  # POST /notices.json
  def create
    @notice = Notice.new(notice_params)

    respond_to do |format|
      if @notice.save
        format.html { redirect_to @notice, notice: 'Notice was successfully created.' }
        format.json { render :show, status: :created, location: @notice }
      else
        format.html { render :new }
        format.json { render json: @notice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notices/1
  # PATCH/PUT /notices/1.json
  def update
    respond_to do |format|
      if @notice.update(notice_params)
        format.html { redirect_to @notice, notice: 'Notice was successfully updated.' }
        format.json { render :show, status: :ok, location: @notice }
      else
        format.html { render :edit }
        format.json { render json: @notice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notices/1
  # DELETE /notices/1.json
  def destroy
    @notice.destroy
    respond_to do |format|
      format.html { redirect_to notices_url, notice: 'Notice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notice
      @notice = Notice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def notice_params
      params.require(:notice).permit(:title, :body, :criation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notices_helper.rb
module NoticesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyNotices</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/notices/_form.html.erb
<div class="form">
	<%= form_for(notice) do |f| %>
	  <% if notice.errors.any? %>
		<div id="error_explanation">
		  <h2><%= pluralize(notice.errors.count, "error") %> prohibited this notice from being saved:</h2>

		  <ul>
		  <% notice.errors.full_messages.each do |message| %>
		    <li><%= message %></li>
		  <% end %>
		  </ul>
		</div>
	  <% end %>

	  <div class="field">
		<%= f.label :title %>
		<%= f.text_field :title, class:"form-control" %>
	  </div>

	  <div class="field">
		<%= f.label :body %>
		<%= f.text_area :body, class:"form-control" %>
	  </div>

	  <div class="field">
		<%= f.label :criation %>
		<%= f.text_field :criation, type:"date", class:"form-control" %>
	  </div>

	  <div class="actions">
		<%= f.submit class:"btn btn-success" %>
	  </div>
	<% end %>
</div>

app/views/notices/edit.html.erb
<div class="container">
	<h1>Editar Notícia</h1>

	<%= render 'form', notice: @notice %>

	<%= link_to 'Detalhes', @notice, class:"btn btn-info" %> 
	<%= link_to 'Voltar', notices_path, class:"btn btn-default"%>
</div>

app/views/notices/index.html.erb
<div class="container">
	<p id="notice"><%= notice %></p>

	<h1>Notices</h1>

	<table class="table">
	  <thead>
		<tr>
		  <th>Título</th>
		  <th>Corpo da Notícia</th>
		  <th>Criação</th>
		  <th colspan="3"></th>
		</tr>
	  </thead>

	  <tbody>
		<% @notices.each do |notice| %>
		  <tr>
		    <td><%= notice.title %></td>
		    <td><%= notice.body %></td>
		    <td><%= notice.criation %></td>
		    <td><%= link_to 'Detalhes', notice, class:"btn btn-info" %></td>
		    <td><%= link_to 'Editar', edit_notice_path(notice), class:"btn btn-default" %></td>
		    <td><%= link_to 'Deletar', notice, class:"btn btn-danger",method: :delete, data: { confirm: 'Tem certeza?' } %></td>
		  </tr>
		<% end %>
	  </tbody>
	</table>

	<br>

	<%= link_to 'Adicionar Notícia', new_notice_path, class:"btn btn-primary" %>
</div>

app/views/notices/new.html.erb
<div class="container">
	<h1>Nova Notícia</h1>

	<%= render 'form', notice: @notice %>

	<%= link_to 'Back', notices_path, class:"btn btn-default" %>
</div>

app/views/notices/show.html.erb
<div class="container">
	<div class="jumbotron">
	<p id="notice"><%= notice %></p>

	<h2>
	  <strong> <%= @notice.title %> </strong> - <%= @notice.criation %>
	</h2>

	<p>
	  <%= @notice.body %>
	</p>

	<%= link_to 'Editar', edit_notice_path(@notice), class:"btn btn-primary" %>
	<%= link_to 'Voltar', notices_path,  class:"btn btn-default"%>
	</div>
</div>